[package]
name = "local-atlas-data-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
mongodb = "2.6.0"
tokio = { version = "1.30.0", features = ["tokio-macros", "rt-multi-thread", "signal"] }
