version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "grafbase"
      MONGO_INITDB_ROOT_PASSWORD: "grafbase"
      INIT_WAIT_SEC: $INIT_WAIT_SEC
    ports:
      - "27018:27017"
    networks:
      - databases

networks:
  databases: null
